version: "3.7"
services:
  jenkins:
      build:
        context: .
      image: jcmds/jenkins:2.237
      container_name: jenkins
      ports:
        - "8080:8080"
      labels:
        NAME: "jenkins"
      volumes:
        - ./data/jobs:/var/jenkins_home/jobs