apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  labels:
    app: jks
    tier: devops
    version: v1  
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jks
    tier: devops
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dep
  labels:
    app: jks
    tier: devops
    version: v1  
spec:
  selector:
    matchLabels:
      app: jks
      tier: devops
      version: v1  
  replicas: 1
  template:
    metadata:
      labels:
        app: jks
        tier: devops
        version: v1  
    spec:
      terminationGracePeriodSeconds: 20
      restartPolicy: Always
      containers:
        - name: jenkins-master
          image: jcmds/jenkins:2.237
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: JENKINS_SERVER_URL
              value: http://$MY_POD_IP:8080
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins_home_job
              mountPath: /var/jenkins_home/jobs      
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "25m"
              memory: "256Mi"
          imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 2000        
      volumes:
      - name: jenkins_home_job
        hostPath:
          path: /host_mnt/d/docker/jenkins-jobs
          type: DirectoryOrCreate 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%