apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
#   namespace: default
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# --- 
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jenkins-vol
#   namespace: default
# spec:
#   storageClassName: local-storage
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# --- 
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: default
  labels:
    app: jenkins
    tier: app
    version: v1  
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: jenkins
    tier: app
    version: v1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dep
  namespace: default
  labels:
    app: jenkins
    tier: app
    version: v1  
spec:
  selector:
    matchLabels:
      app: jenkins
      tier: app
      version: v1  
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        tier: app
        version: v1  
    spec:
      terminationGracePeriodSeconds: 10
      restartPolicy: Always
      containers:
        - name: jenkins-master
          image: jcmds/jenkins:2.236
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: JENKINS_SERVER_URL
              value: http://$MY_POD_IP:8080
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          # volumeMounts:
          #   - name: jenkins-vol
          #     mountPath: /var/jenkins_home   
          resources:
            requests:
              cpu: 25m
              memory: 200Mi
          imagePullPolicy: IfNotPresent
      # volumes:
      #   - name: jenkins-vol
      #     persistentVolumeClaim:
      #       claimName: jenkins-vol   
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%