apiVersion: "v1"
kind: "Pod"
spec:
  containers:
  - image: "lachlanevenson/k8s-kubectl:latest"
    imagePullPolicy: "IfNotPresent"
    name: "kubectl"
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"
      requests:
        cpu: "25m"
        memory: "256Mi"
    securityContext:
      privileged: true
    tty: true
    command:
      - "cat"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  - image: "docker"
    imagePullPolicy: "IfNotPresent"
    name: "docker"
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "25m"
        memory: "256Mi"
    securityContext:
      privileged: true
    tty: true
    command:
    - "cat"
    volumeMounts:
    - mountPath: "/var/run/docker.sock"
      name: "volume-0"
      readOnly: false
    - mountPath: "/home/jenkins/agent"
      name: "workspace-volume"
      readOnly: false
  restartPolicy: "Never"
  volumes:
  - hostPath:
      path: "/var/run/docker.sock"
    name: "volume-0"
  - emptyDir:
      medium: ""
    name: "workspace-volume"